import type { NextPage } from 'next'
import Head from 'next/head'

import { trpc } from '../utils/trpc'

const Home: NextPage = (props: any) => {
  const { data, isLoading } = trpc.useQuery(["getAllQuestions"]);

  if (isLoading || !data) return <p>Loading...</p>;

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-3xl font-bold underline">
          Hello world!
        </h1>

        <div>
          {data[0]?.question}
        </div>
      </main>
    </div>
  )
}

export default Home
