import type { NextPage } from 'next'
import Head from 'next/head'

import { prisma } from '../db/client'
import { trpc } from '../utils/trpc'

const Home: NextPage = (props: any) => {
  const { data, isLoading } = trpc.useQuery(["hello"]);

  if (isLoading || !data) return <p>Loading...</p>;

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-3xl font-bold underline">
          Hello world!
        </h1>

        <div>
          {data.greeting}
        </div>

        <code>
          {props.questions}
        </code>
      </main>
    </div>
  )
}

export default Home

export const getServerSideProps = async () => {
  const questions = await prisma.pollQuestion.findMany();

  return {
    props: {
      questions: JSON.stringify(questions)
    }
  }
}
